version: "3.9"
services:
  app:
    restart: always
    build: .
    environment:
      ConnectionStrings__DefaultConnection: "Server=database;Port=5432;Database=app;User Id=app;Password=Aidohjokaotohpiashaa2iake7sheiF9aixu4Uox;"
      ASPNETCORE_ENVIRONMENT: Production
      VIRTUAL_HOST: skilltracker.local,skilltracker.tobiass.nl
      LETSENCRYPT_HOST: skilltracker.tobiass.nl
    env_file:
      - .env
    expose:
      - 80
    depends_on:
      - database
    networks:
      - proxy
      - app


  database:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: Aidohjokaotohpiashaa2iake7sheiF9aixu4Uox
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - app

networks:
  app:
  proxy:
    external: true

volumes:
  database:
